-- Generated by tools/prepare_familiars.py. Do not edit by hand.
-- description is intentionally left NULL: the ability text lives in the owner's
-- design document and is not duplicated here.
INSERT INTO familiars (id, name, kind, variants, image_version, is_listed, sort_order) VALUES
  ('familiar_mirror', 'Осколок зеркала', 'creature', 'day1,day2,day3,night', 'be230ce7', 1, 10),
  ('familiar_vaynera_spirit', 'Дух улицы Вайнера', 'creature', 'day1,day2,day3,night', 'fa6d2e1e', 1, 20),
  ('familiar_weird_compass', 'Компас "туда где странно"', 'creature', 'day1,day2,day3,night', 'eef2dcb3', 1, 30),
  ('familiar_gentlemans_tear', 'Кубок "Слеза джентльмена"', 'creature', 'day1,day2,day3,night', '10bec8ea', 1, 40),
  ('familiar_dobyvala', 'Добывала', 'creature', 'day1,day2,day3,night', '12f38f45', 1, 50),
  ('familiar_abyss_eater', 'Зев бездны', 'creature', 'day1,day2,day3,night', '044fe85b', 1, 60),
  ('familiar_earth_cat', 'Земляная кошка', 'creature', 'day1,day2,day3,night', 'c380abca', 1, 70),
  ('familiar_malachite_lizard', 'Малахитовая ящерица', 'creature', 'day1,day2,day3,night', '3ab04c06', 1, 80),
  ('familiar_fox', 'Чудо-лиса', 'creature', 'day1,day2,day3,night', 'e8e9cdb2', 1, 90),
  ('familiar_ping_penguin', 'Пингвин Пинг', 'creature', 'day1,day2,day3,night', '922bab82', 1, 100),
  ('familiar_five_more_minutes', 'Ещё пять минут', 'creature', 'day1,day2,day3,night', '48220241', 1, 110),
  ('familiar_public_wifi', 'Кусочек общественного Wi-Fi', 'creature', 'day1,day2,day3,night', 'd8bd6e17', 1, 120),
  ('familiar_arkady', 'Бомж-пророк Аркадий', 'creature', 'day1,day2,day3,night', '1c5484d4', 1, 130),
  ('familiar_bad_advice', 'Дух плохого совета', 'creature', 'day1,day2,day3,night', '7d54e20c', 1, 140),
  ('familiar_told_you_raven', 'Ворон «Я же говорил»', 'creature', 'day1,day2,day3,night', '78adda71', 1, 150),
  ('familiar_bureaucracy_imp', 'Мелкий бес бюрократии', 'creature', 'day1,day2,day3,night', 'b190cda1', 1, 160),
  ('familiar_common_sense_toad', 'Жаба здравого смысла', 'creature', 'day1,day2,day3,night', '238899db', 1, 170),
  ('familiar_literal_pigeon', 'Голубь-почтальон', 'creature', 'day1,day2,day3,night', '51281e1b', 1, 180),
  ('familiar_unread_notifications', 'Барабашка непрочитанных уведомлений', 'creature', 'day1,day2,day3,night', 'b2e622be', 1, 190),
  ('familiar_lost_things', 'Дух потерянных вещей', 'creature', 'day1,day2,day3,night', 'f842ff53', 1, 200),
  ('familiar_glazastik', 'Глазастик', 'creature', '', '1', 0, 901),
  ('familiar_dancefloor_queen', 'Королева Танцпола', 'creature', '', '1', 0, 902),
  ('familiar_player_kristina', 'Матеюнс Кристина Валерьевна', 'player', '', '1', 0, 903);
